### ISSUE TITLE
这个一个我看过再伟大的工程了，谢谢执着

### ISSUE THREAD

**Issue by cutepan** [zhizhuoshuma/WechatBot#4]
这个一个我看过再伟大的工程了，谢谢执着
望期待添加openai
还有那个推送不能推送给个人微信ID ，望修复。
很期待更新呢。

**Comment by cutepan** [comment]
还有那个新闻推送，能换上其他的新闻平台就完美了。
或者用一些其他新闻接口网站API json 格式化就好了

**Comment by kkx600** [comment]
因为设计的初衷就是为网络安全行业设计的，这些功能可以在httpcli中进行自定义修改的。
